### PR TITLE
add configurable static layouts sorting

### PR DESCRIPTION
**Pull request by mjauvin**
- Add config setting to choose key used to sort static layouts options (defaults to created_at to maintain current behavior)
- Fetch this setting and sort results based on that key

### CODE REVIEW

**Comment by LukeTowers** [comment]
Aren't these sorted by the layout name?

**Comment by mjauvin** [comment]
Keyed by, but looks like created_at for the query sorting. I'll double
check.

--
Marc

**Comment by bennothommo** [comment]
@mjauvin What sort of use case would you need to change the order for? I'm cautious of adding unneeded complexity.

**Comment by LukeTowers** [comment]
@mjauvin I don't think this is the right approach if a change is even required. I would be more inclined to have something like an order property set on the layout to define the order of the layouts in the dropdown.

**Comment by mjauvin** [comment]
@LukeTowers you mean add an order property for dropdown formfield types in general?

**Comment by mjauvin** [comment]
I don't care about this one, let's drop it.

**Comment by LukeTowers** [comment]
@mjauvin I mean like
```ini
name = "Default layout"
order = 500
==
<?php
?>
==
Twig
```

**Pull request closed without merging**
