### PR TITLE
Add type property to staticMenu component items

### PR DESCRIPTION
**Pull request by damsfx**
Try to offer a solution to #171

### CODE REVIEW

**Comment by bennothommo** [comment]
On hold, pending the results of the discussions here: https://github.com/rainlab/pages-plugin/issues/171#issuecomment-693794445

**Comment by LukeTowers** [comment]
@bennothommo should be good for testing / merging now, will let you do that since I'm not on top of the release cycle here

**Comment by bennothommo** [comment]
@damsfx The `type` parameter will also need to be populated here: https://github.com/rainlab/pages-plugin/blob/09eb2e6a7be02cb5abde879627c05ea59d27c2bd/classes/Menu.php#L191

**Comment by daftspunk** [comment]
LGTM

**Pull request merged**
