### PR TITLE
Use locales in URLs

### PR DESCRIPTION
**Pull request by MatissJanis**
Basic Rainlab.Translate plugin support.

### CODE REVIEW

**Comment by daftspunk** [comment]
This assumes the developer is using the URL to set the locale, using the locale picker can store it in the session.

This should be solved by [Customizing the default markup for staticMenu]( http://octobercms.com/docs/cms/components#customizing-default-markup) instead.

**Comment by daftspunk** [comment]
Example:

{% for item in items %}
    <li class="{{ item.isActive ? 'active' : '' }} {{ item.isChildActive ? 'child-active' : '' }}">
        <a href="{{ activeLocale }}/{{ item.url }}">{{ item.title }}</a>

        {% if item.items %}
            <ul>{% partial __SELF__ ~ "::items" items=item.items %}</ul>
        {% endif %}
    </li>
{% endfor %}

**Comment by MatissJanis** [comment]
Setting the locale this way wouldn't work as ` item.url` is full URL (e.g. http://localhost/page`) and not just the URI.

Would You have any other ideas how to solve this problem?

**Comment by YuccaOne** [comment]
Hi,
With
<code><a href="{{ activeLocale }}/{{ item.url }}">{{ item.title }}</a></code>
my URL is locale + item.url :
if locale is on 'fr' and my page 'contact', I have 'fr/http://domain.ltd/contact'

Thanks

**Pull request closed without merging**
