### PR TITLE
Add static page component properties "default" and "childLayout"

### PR DESCRIPTION
**Pull request by jimcottrell**
Continuing to move our UX customizations upstream, we wanted more flexibility specifying the default layout for new pages.  This pull request adds a `default` property to define a layout as the global default.  It also adds a `childLayout` property which can override that on subpages based on the parent page's layout.  If no default is specified, no special action will be taken, resulting in the current behavior of defaulting to the first available layout in the form dropdown.

### CODE REVIEW

**Comment by Eoler** [comment]
This is great, could it be packed into "pending" version of plugin for testing?

**Comment by LukeTowers** [comment]
@Eoler I've bumped the version: https://github.com/rainlab/pages-plugin/commit/c942968b6804e8eef8642bebbd91d82af9b6462a.

I don't know if @daftspunk has autodeploy setup on this repository to the plugin marketplace, but it should appear there soon.

**Comment by Eoler** [comment]
It got picked by the Check for updates, thanks.
Making layout default should ease adding pages for customers, great addition.

**Comment by jBOKA** [comment]
Version 1.2.17 seems not to appear on the marketplace, can you check on that @LukeTowers ?
Thanks in advance!

**Comment by LukeTowers** [comment]
It is, it's just marked as a Pending update, which means that you need to enableEdgeUpdates in config/cms.php to get it.

**Comment by jBOKA** [comment]
Cool, thanks

**Pull request merged**
