### PR TITLE
Allow extensibility of MenuItem fields

### PR DESCRIPTION
**Pull request by agentk**
Hi All,

I needed to extend the MenuItem fields for a client. This is what I ended up needing to change in the pages-plugin. It's pretty minimal. I tried to get the client to enter strings into the 'code' field for menu items, but it was not ideal with the amount of confusion it caused.

For example, if I need to add a featured field to MenuItems I can use:

    public function boot()
    {
        Event::listen('rainlab.pages.menuitem.create', function ($obj) {
            $obj->featured = false;
            $obj->basicProperties[] = 'featured';
            $obj->fillable[] = 'featured';
        });

        Event::listen('backend.form.extendFields', function ($widget) {

            if (!$widget->getController() instanceof \RainLab\Pages\Controllers\Index ||
                !$widget->model instanceof \RainLab\Pages\Classes\MenuItem) {
                return;
            }

            $widget->addSecondaryTabFields([
                'featured' => [
                    'tab' => 'Display',
                    'label' => 'Featured',
                    'comment' => 'Mark this menu item as featured',
                    'type' => 'checkbox'
                ]
            ]);
        });
    }

If you have a better way of accomplishing the task, I'm all ears.

### CODE REVIEW

**Comment by daftspunk** [comment]
This looks really good, the only thing I'm not sure about is the dynamic creation of the `featured` property with code `$obj->featured = false;`. Also, how are you grabbing the value on the front-end, I assume the MenuItemReference won't contain this data?

**Comment by agentk** [comment]
True true. I would prefer to be able to specify available fields in the `$obj->fillable` array alone. But when restoring properties from the yaml file, `initFromArray` wants the field available as a property on the object.

Should I refactor `initFromArray` a bit too? I might be able to get it down to only having to specify the extra fields from the backend.form.extendFields event.

I missed the MenuItemReference in my first commit. In the template files the fillable property is used from `$item->featured` like:
```twig
{% for item in items %}
    <li class="navigation__item{{ item.isActive ? ' active' : '' }}{{ item.featured ?  ' navigation__item--feature' : '' }}">
        <a class="navigation__link{{ item.featured ? ' navigation__link--feature' : '' }}" href="{{ item.url }}">
            {{ item.title }}
        </a>
    </li>
{% endfor %}
```

**Comment by daftspunk** [comment]
We spent some more time thinking about this... the key question that came up was "How is this possible using CMS pages/partials/layouts/etc currently?" Well, the answer is to use the `viewBag` component:

        Event::listen('backend.form.extendFields', function ($widget) {

            if (!$widget->getController() instanceof \Cms\Controllers\Index ||
                !$widget->model instanceof \Cms\Classes\Page) {
                return;
            }

            $widget->addTabFields([
                'viewBag[featured]' => [
                    'tab' => 'Display',
                    'label' => 'Featured',
                    'comment' => 'Mark this page as featured',
                    'type' => 'checkbox'
                ]
            ]);
        });

It's a special component used for storing arbitrary data. The above extension would result in the following value stored on the page:

    title = "Home"
    url = "/home"

    [viewBag]
    featured = "1"

There is nothing special about this, it "just works". There is no need to modify any `$fillable` property or anything because the object is expecting custom values here. This gave us precedence (to borrow a legal term) to use this pattern as a solution. So with this in mind, you can use the following code:

    Event::listen('backend.form.extendFields', function ($widget) {

        if (!$widget->getController() instanceof \RainLab\Pages\Controllers\Index ||
            !$widget->model instanceof \RainLab\Pages\Classes\MenuItem) {
            return;
        }

        $widget->addSecondaryTabFields([
            'viewBag[featured]' => [
                'tab' => 'Display',
                'label' => 'Featured',
                'comment' => 'Mark this menu item as featured',
                'type' => 'checkbox'
            ]
        ]);
    });

Resulting in a stored menu configuration of:

    -
        title: Home
        type: cms-page
        code: ''
        reference: home
        viewBag:
            featured: '1'

Then made available in the markup as `{{ item.viewBag.featured }}`, for example:

    {% for item in items %}
        <li class="navigation__item{{ item.isActive ? ' active' : '' }}{{ item.viewBag.featured ?  ' navigation__item--feature' : '' }}">
            <a class="navigation__link{{ item.viewBag.featured ? ' navigation__link--feature' : '' }}" href="{{ item.url }}">
                {{ item.title }}
            </a>
        </li>
    {% endfor %}

See 0344f642539f25698069fa9984f73ed51426d7ec

**Comment by daftspunk** [comment]
Also, could you open another PR with your *Recursively extract page placeholder nodes* commit?

**Pull request closed without merging**
