### PR TITLE
Adding Robots META fields

### PR DESCRIPTION
**Pull request by FlusherDock1**
Same as Core [#4685](https://github.com/octobercms/october/pull/4685).

Problem here, i can't find the way to get it work. Is there any method that pushes data from viewBag to settings array of Page class?

### CODE REVIEW

**Comment by bennothommo** [comment]
@FlusherDock1 I'd say it's this line here:
https://github.com/rainlab/pages-plugin/blob/master/classes/Controller.php#L57

**Comment by FlusherDock1** [comment]
@bennothommo thanks for the tip. Can't find that. 

Pushed new commit, everything works as it should.

**Comment by bennothommo** [comment]
@FlusherDock1 Thanks for that. Once it's confirmed by the team that it's working, it's as good as merged.

**Comment by bennothommo** [comment]
Closing this as it appears that the original PR to the core was reverted: https://github.com/octobercms/october/pull/4685#issuecomment-567186308

**Pull request closed without merging**
