### PR TITLE
Add array support for repeaters

### PR DESCRIPTION
**Pull request by jonpxpx**
Fixes issue with repeaters not working in Static pages.

Fileuploader is ignored but I will look into a possible solution around this when I have more time.

### CODE REVIEW

**Comment by jonpxpx** [comment]
Turns out this code works, but due to the additional tabs added to each row of the repeater... It breaks the tab-id's so any of the top level tabs (primary-tabs).

Top Level Tabs (Settings, Meta, Repeater 1, Normal Tab, Normal Tab 2)

Without a row added to "Repeater 1", you can switch between all of the above tabs.
Adding a single row to "Repeater 1" is fine until you refresh the page.

Once refreshed, you can open the tabs for Settings, Meta, Repeater 1 but you can't open any tabs after.

My only assumption is that tabs within repeaters are stealing the ID's and therefore Primary tabs can no longer match. Do we need a new tab naming convention for the tabs residing in the repeaters?

**Comment by surahmans** [comment]
+1

**Comment by jonpxpx** [comment]
@daftspunk Any thoughts on the tab issues I've raised?

**Comment by surahmans** [comment]
I have a deadline project and I hope the issues will be fix within or less than 3 days.
@daftspunk

**Comment by jonpxpx** [comment]
@surahmans I am in a similar situation, although I may try and look into the issue with the core tab js.

**Comment by surahmans** [comment]
@jonpxpx Have you fixed this?
For now, I just put all of repeaters in same tab. So I can add more than one repeaters in a page and the tabs are switchable.

**Comment by jonpxpx** [comment]
Not at the moment @surahmans, I haven't had time to even look at it yet.

**Comment by daftspunk** [comment]
Thanks!

**Comment by jonpxpx** [comment]
Thanks for rolling this out Sam, apologies for the slight mistake on the fields and again thanks for fixing the tabbing issue.

**Pull request merged**
