### PR TITLE
Create lang.php

### PR DESCRIPTION
**Pull request by merodeador**
Adds spanish language file.

### CODE REVIEW

**Comment by FelixINX** [comment]
Invalid : the file is `lang.` and not `lang.php`

Please change it :smiley:

**Comment by merodeador** [comment]
sorry i mistyped. fixed it ;-)

**Comment by FelixINX** [comment]
Ok thats should be ok. Now we have to wait for @daftspunk

**Comment by daftspunk** [comment]
Thanks

**Pull request merged**
