### PR TITLE
add link target attribute

### PR DESCRIPTION
**Pull request by whsol**

### CODE REVIEW

**Comment by daftspunk** [comment]
Please provide a screenshot of the resulting form layout. Just need to make sure it still looks OK.

**Comment by whsol** [comment]
pages-close


pages

**Comment by hybridvision** [comment]
This is a useful addition and it raises a question: what is the best way to extend the plugin to add small features like this?

I need to assign a custom CSS class to certain menu items and I see someone else has already done that here: https://github.com/lgt/pages-plugin/commit/2a0b64164451ca9966212cfff9a2c83ea58e250d

However, I'm wondering if there is a better way since these changes will be lost each time the plugin is updated? Any advice @daftspunk?

Thanks!

Stephen

**Comment by daftspunk** [comment]
Both of these instances can be handled by the "Code" field, for example it could contain all the CSS classes you want. Or you could use it to say `open-in-new-window`.

Then by [Customizing the default markup for staticMenu]( http://octobercms.com/docs/cms/components#customizing-default-markup) you could look for the code and modify the markup.

Eg:

```
<a
    href="{{ item.url }}"
    {% if 'open-in-new-window' in item.code %}target="_blank"{% endif %}
>{{ item.title }}</a>
```

**Comment by hybridvision** [comment]
Thanks @daftspunk! That's actually what I tried originally but `item.code` never seems to get set - it is a null value when I try to use it (with latest build 260 and v1.0.12 of the pages plugin).

Am I missing something here? Do you get a value when you've filled in the code field and then use `item.code`?

**Comment by daftspunk** [comment]
`item.code` should be available now.

The interface will be improved to add target and class soon.

**Comment by daftspunk** [comment]
This is fixed more thoroughly in v1.1.7

**Pull request closed without merging**
