### PR TITLE
Added cssClass field to StaticMenu component.

### PR DESCRIPTION
**Pull request by donaldej**
Each staticMenu list item will have its own cssClass like usual, but I added an cssClass field to the staticMenu itself so that the unordered list element also can contain a class name.

### CODE REVIEW

**Comment by alexgann** [comment]
Would be awesome if this could be merged - need precisely this functionality.

**Comment by daftspunk** [comment]
Menu Items already have CSS Class under the *Attributes* tab.

**Comment by daftspunk** [comment]
The CSS class can be added by overriding the component markup. [See the documentation](http://octobercms.com/docs/cms/components#overriding-partials) on how this is done. It doesn't really make much sense to add a form field to add a CSS class to the container when this can be done via the theme

**Comment by donaldej** [comment]
So.... override the entire markup to add a class to the container vs just populating a text input?

**Comment by alexgann** [comment]
The obvious use-case here is going to be something like twitter bootstrap which requires `<ul class="nav navbar-nav">` on the primary menu ul.

I've tried overriding the partial by placing a new default.htm in themes/mytheme/partials/staticmenu/default.htm but it does not seem to be overloading.  I tried `artisan cache:clear` just in case.  Based on [the comment here](https://github.com/octobercms/october/issues/44#issuecomment-88907831) it would seem that maybe default.htm can't be overridden?

Thanks @daftspunk for the great work - just looking for the best way to handle this.

**Comment by alexgann** [comment]
Doesn't seem to be anything special on default.htm - can't get items.htm to override either.  Maybe I have the path wrong?

In plugin path is: `plugins/rainlab/pages/components/staticmenu/items.htm`
In theme path is: `themes/ntgreek/partials/staticmenu/items.htm`

**Pull request closed without merging**
