### PR TITLE
Added event to provides opportunity to supplement the snippet configuration.

### PR DESCRIPTION
**Pull request by bereznev**
…ration.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Why wouldn't you just use components at this point?

**Comment by panki3a** [comment]
Because, we use component in the snipet. And this snipet we put it into static page via editor. So we need pass paramter id gallery through  wysiwyg editor.

**Comment by LukeTowers** [comment]
Can you provide the code involved in what you just described along with how you'd be using this event?

**Comment by bereznev** [comment]
for example: https://github.com/rainlab/pages-plugin/pull/462/commits/4bb30dda050f7cb779776b4a4a4c737f7982588b#diff-5a8581e5f13e78e2f6f0c8ce2503b020R337

**Comment by LukeTowers** [comment]
@bereznev I need a more specific example which would communicate to me how a component is unsuitable for your desired task.

**Comment by panki3a** [comment]
We need tu generete list of Galeries ids and slugs, into snipet options. 
User can put snipet into static page and can choose ID of galerie from dropdown menu of this snipet.
So we need the option how to put list of galeries into this snipet.

**Comment by LukeTowers** [comment]
@panki3a you said that. Snippets aren't meant for super complex use cases though, so I need to know why Components, which are meant for exactly that use case and can be used as snippets, fail to meet your need.

**Comment by panki3a** [comment]
Becouse, they dont wont to use it in CMS page, but in STATIC PAGE with WYSYGN editor. 
They create new static page, for example article about new product, and they want to put into page GALERY.
So they use snipet, put it into page through wysygn editor, and they choose from dropdown menu specific ID Galery

**Comment by mjauvin** [comment]
right, but you use the plugin's registerSnippets() method, you can make a component become a snippet usable in Static Pages...

**Comment by panki3a** [comment]
No, it doesnt work. We couldnt appent snipet, to render list of galeries in snipet in backend editor.

**Comment by panki3a** [comment]
> right, but you use the plugin's registerPageSnippets() method, you can make a component become a snippet usable in Static Pages...
> 
> ref. https://github.com/rainlab/pages-plugin/blob/master/docs/documentation.md#snippets-created-from-components

In example in documentation, you can only create option list for snipet manualy.
`{variable name="tagline" label="Tagline" tab="Header" type="text"}{/variable}
{variable name="banner" label="Banner" tab="Header" type="mediafinder" mode="image"}{/variable}
{variable name="color" label="Color" tab="Header" type="dropdown"
    options="blue:Blue | orange:Orange | red:Red"
}{/variable}`

But we need to generate this options dynamically, from DB

**Comment by mjauvin** [comment]
what do you mean "option list for snippet" ? If your snippet is based on a component, the component/snippet option list can be generated from a component method (e.g. getColorOptions() ).

**Comment by panki3a** [comment]
Can you give me the documentation link or example? Becouse we didn't found the way how to put  the galeries list even like this:
`Event::listen('pages.content.snippetConfiguration', function (array $newConfiguration, string $snippetCode) {
            if ($snippetCode === Gallery::SNIPPET_CODE) {
                $data = GalleryModel::query()
                    ->select('id', 'name')
                    ->get()
                    ->mapWithKeys(fn (GalleryModel $model) => [$model->id => $model->name])
                    ->all();
                $newConfiguration[0]['options'] = $data;
            }
            return $newConfiguration;
        });`
and put this into snipet:
`description = "Galeria"

[medirexGallery]

[viewBag]
snippetCode = "post-gallery"
snippetName = "Galeria"
snippetProperties[galleryId][title] = "ID Galerie"
snippetProperties[galleryId][type] = "dropdown"
snippetProperties[galleryId][default] = ""
snippetProperties[galleryId][options][0] = "0"

==
<?php
function onStart()
{
    $this['snippetGalleryId'] = $this->controller->vars['galleryId'];
}
?>
==
{% component 'gallery' idGallery=snippetGalleryId %}

`

**Comment by mjauvin** [comment]
But did you create a component?

The component should be added to your CMS page (or snippet added to Static Page), why use the viewBag and `pages.content.snippetConfiguration` event here?

**Comment by panki3a** [comment]
Becouse we need it in STATIC PAGE, not CMS page. Yes we have component, which is use in snipet.
But the client he want to use only in STATIC PAGE, in wysygn editor.
And even more, he want to have dynamically rendered dropdown menu, with list of galeries ids

**Comment by mjauvin** [comment]
Ok, so when editing this Static Page on the backend, click on "Snippets" on the left hand side and select your Snippet to add to your Static Page.

Make sure you register your component as a snippet using registerPageSnippets().

**Comment by panki3a** [comment]
What do you mean ? We did it. But there isn't way how to put dynamically list of galeries ids. 
If so, can you show me real example how to do this ? Because we realy spent hours of search the forums, stack or documentations. And we didn't find other way.

**Comment by mjauvin** [comment]
Can you put your plugin on a github repo so I can test on my end and see what you're missing?

**Comment by LukeTowers** [comment]
https://github.com/rainlab/pages-plugin/blob/master/docs/documentation.md#snippets

> Snippets can be created from partials or programmatically in plugins. Conceptually snippets are similar to CMS components (and technically, components can act as snippets).

https://github.com/rainlab/pages-plugin/blob/master/docs/documentation.md#snippets-created-from-components

If your component has been setup properly to use Dropdown properties that are dynamically generated (see https://octobercms.com/docs/plugin/components#dropdown-properties) then it will work exactly the same as a Snippet in RainLab.Pages static pages as it would as a regular component for CMS templates.

**Comment by panki3a** [comment]
@LukeTowers thank you. You are right.
It's works.
I can't believe, that we miss something. We really spent hours to find solutions, and we invent the wheel :(
My excuse for that.
So you can clouse this PR. It's useless.

**Comment by LukeTowers** [comment]
@panki3a no worries. Could you look over the docs again and submit a PR with your recommendations on where you would expect to see that information so that no one else is confused about the functionality in the future?

**Comment by panki3a** [comment]
I will look on it.

**Pull request closed without merging**
